import { Facebook, GitHub, LinkedIn, Twitter } from "@material-ui/icons";

const data = {
  name: "Kapena Peter Lumumba",
  job: "Software Developer - Full Stack",
  email: "peterkapenapeter@gmail.com",
  languages: "English & French",
  socials: [
    {
      icon: <Facebook></Facebook>,
      link: "https://www.facebook.com/peterkapenapeter",
    },
    {
      icon: <Twitter></Twitter>,
      link: "https://twitter.com/Pkapenapeter",
    },
    {
      icon: <GitHub></GitHub>,
      link: "https://github.com/peterkapena",
    },
    {
      icon: <LinkedIn></LinkedIn>,
      link: "https://www.linkedin.com/in/kapena-peter-lumumba-7344b8158/",
    },
  ],
  expertise: [
    ".NET",
    "ASP.NET Core",
    ".NET Framework",
    "Blazor, Razor, MVC & SPA",
    "C#",
    "Visual Basic",
    "JavaScript",
    "React JS",
    "Material UI",
    "Bootstrap",
    "Node JS",
    "jQuery",
    "React Native",
    "Dart, Flutter",
    "Ms SQL Server",
    "MongoDB",
    "AWS DynamoDB",
    "MySQL",
    "C / C++",
    "Java",
  ],
  skills: [
    "REST API",
    "SOAP Services",
    "GraphQL",
    "AWS AppSync",
    "AWS Amplify",
    "Hot Chocolate (.NET)",
    "Google Remote Procedures Call - GRPC",
    "AWS",
    "Azure",
    "Google Cloud",
    "Firebase",
    "Visual Studio, VS Code, Android Studio",
    "Git",
    "Azure DevOps",
    "GitHub",
    "Microsoft server",
    "Ubuntu - Linux",
    "Microsoft IIS",
    "DevOps",
  ],
};
export default data;
